#!/bin/sh

UPSTREAM_1_HOST=$UPSTREAM_1_HOST
UPSTREAM_2_HOST=$UPSTREAM_2_HOST
UPSTREAM_1_USER_PASS=$UPSTREAM_1_USER_PASS
UPSTREAM_2_USER_PASS=$UPSTREAM_2_USER_PASS
UPSTREAM_PROXY_PORT=$UPSTREAM_PROXY_PORT

export UPSTREAM_1_HOST UPSTREAM_2_HOST UPSTREAM_1_USER_PASS UPSTREAM_2_USER_PASS UPSTREAM_PROXY_PORT

envsubst < /etc/squid/squid.conf.template > /etc/squid/squid.conf

squid -f /etc/squid/squid.conf -N